services:
  app:
    build: .
    container_name: python-server
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/code
    depends_on:
      - redis
    network_mode: host


  redis:
    image: redis:alpine
    network_mode: host
